server:
  port: 3344


spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gay88358/spring-cloud-config.git
          search-paths:
            - spring-cloud-config
      label: master


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
