server:
  port: 9527


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#  cloud:
#    gateway:
#      routes:
#          - id: route2
#            uri: http://localhost:8002
#            predicates:
#              - Path=/payments/lb
#

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/


