server:
  port: 80


spring:
  application:
    name: cloud-order-service


eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka # register payment with eureka cluster
  instance:
    instance-id: order80
    prefer-ip-address: true


# which can modify read timeout and connect timeout so that the long business transaction didn't encounter timeout
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


logging:
  level:
    com.mars.hong.PaymentFeignService: debug