server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181


# zookeeper version
# zookeeper.version=3.5.9-83df9301aa5c2a5d284a9940177808c01bc35cef
